version: '3.7'
services:
  baseImage:
    image: base
    env_file: ${ENV_FILE}
    build: .
  backend:
    image: base
    # ports:
    #   - '4000:4000'
    command: >
      sh -c "npm run deploy:backend && 
             npm run seed:backend &&
             npm run start:backend"
    env_file: ${ENV_FILE}
    depends_on:
      - prisma
      - mysql
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./deploy/nginx/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - 80:80/tcp
    depends_on:
      - backend
      - dashboard
    restart: always
    env_file: ${ENV_FILE}
  dashboard:
    image: base
    # ports:
    #   - '1234:1234'
    command: >
      sh -c "npm run build:dashboard && 
             npm run start:dashboard"
    restart: always
    env_file: ${ENV_FILE}
    depends_on:
      - backend
    volumes:
      - ./build-cache:/app/packages/dashboard/.cache
  prisma:
    restart: on-failure
    image: prismagraphql/prisma:1.34.8
    env_file: ${ENV_FILE}
    depends_on:
      - mysql
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mysql
            host: mysql
            user: ${MYSQL_USER}
            password: ${MYSQL_PASS}
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    restart: on-failure
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ./persistence/mysql:/var/lib/mysql
