const TOGGLE_SHARE_BUTTON = 'TOGGLE_SHARE_BUTTON';
const TOGGLE_SESSION_MODAL = 'TOGGLE_SESSION_MODAL';
const TOGGLE_SESSION_DRAWER = 'TOGGLE_SESSION_DRAWER';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const TOGGLE_ASSIGN_MODAL = 'TOGGLE_ASSIGN_MODAL';
const ADD_ACTIVITY = 'ADD_ACTIVITY';

export default {
  TOGGLE_SHARE_BUTTON,
  TOGGLE_SIDEBAR,
  TOGGLE_SESSION_MODAL,
  TOGGLE_ASSIGN_MODAL,
  TOGGLE_SESSION_DRAWER,
  ADD_ACTIVITY,
};
