const SET_CURRENT_USER = 'SET_CURRENT_USER';
const GET_CURRENT_USER = 'GET_CURRENT_USER';
const LOGOUT_USER = 'LOGOUT_USER';

export default {
  SET_CURRENT_USER,
  GET_CURRENT_USER,
  LOGOUT_USER,
};
